# Generated by Django 4.2.1 on 2023-06-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
