# Generated by Django 4.2.1 on 2023-06-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_remove_task_tags_task_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tags',
            new_name='tag',
        ),
    ]
